# Generated by Django 2.1.4 on 2019-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190121_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_empty', models.BooleanField()),
            ],
        ),
    ]
